export const CONTINENTS = ['Africa', 'Asia', 'Europe', 'North America', 'South America', 'Oceania'];

// Maps both the world-atlas map dataset's country names and our own dataset's
// country names (see data/build_data.py's COUNTRY dict) to one of the six
// continents above. A few names differ between the two sources (e.g. "United
// States" vs "United States of America") and a few of our own countries
// (Hong Kong, Singapore) aren't present as distinct shapes in the low-res map
// data — those are added as manual aliases at the end so continent filtering
// still works for them even though they have no clickable shape on the map.
export const COUNTRY_CONTINENT = {
  Afghanistan: 'Asia',
  Albania: 'Europe',
  Algeria: 'Africa',
  Angola: 'Africa',
  Argentina: 'South America',
  Armenia: 'Asia',
  Australia: 'Oceania',
  Austria: 'Europe',
  Azerbaijan: 'Asia',
  Bahamas: 'North America',
  Bangladesh: 'Asia',
  Belarus: 'Europe',
  Belgium: 'Europe',
  Belize: 'North America',
  Benin: 'Africa',
  Bhutan: 'Asia',
  Bolivia: 'South America',
  'Bosnia and Herz.': 'Europe',
  Botswana: 'Africa',
  Brazil: 'South America',
  Brunei: 'Asia',
  Bulgaria: 'Europe',
  'Burkina Faso': 'Africa',
  Burundi: 'Africa',
  Cambodia: 'Asia',
  Cameroon: 'Africa',
  Canada: 'North America',
  'Central African Rep.': 'Africa',
  Chad: 'Africa',
  Chile: 'South America',
  China: 'Asia',
  Colombia: 'South America',
  Congo: 'Africa',
  'Costa Rica': 'North America',
  Croatia: 'Europe',
  Cuba: 'North America',
  Cyprus: 'Europe',
  Czechia: 'Europe',
  "Côte d'Ivoire": 'Africa',
  'Dem. Rep. Congo': 'Africa',
  Denmark: 'Europe',
  Djibouti: 'Africa',
  'Dominican Rep.': 'North America',
  Ecuador: 'South America',
  Egypt: 'Africa',
  'El Salvador': 'North America',
  'Eq. Guinea': 'Africa',
  Eritrea: 'Africa',
  Estonia: 'Europe',
  Ethiopia: 'Africa',
  'Falkland Is.': 'South America',
  Fiji: 'Oceania',
  Finland: 'Europe',
  France: 'Europe',
  Gabon: 'Africa',
  Gambia: 'Africa',
  Georgia: 'Asia',
  Germany: 'Europe',
  Ghana: 'Africa',
  Greece: 'Europe',
  Greenland: 'North America',
  Guatemala: 'North America',
  Guinea: 'Africa',
  'Guinea-Bissau': 'Africa',
  Guyana: 'South America',
  Haiti: 'North America',
  Honduras: 'North America',
  Hungary: 'Europe',
  Iceland: 'Europe',
  India: 'Asia',
  Indonesia: 'Asia',
  Iran: 'Asia',
  Iraq: 'Asia',
  Ireland: 'Europe',
  Israel: 'Asia',
  Italy: 'Europe',
  Jamaica: 'North America',
  Japan: 'Asia',
  Jordan: 'Asia',
  Kazakhstan: 'Asia',
  Kenya: 'Africa',
  Kosovo: 'Europe',
  Kuwait: 'Asia',
  Kyrgyzstan: 'Asia',
  Laos: 'Asia',
  Latvia: 'Europe',
  Lebanon: 'Asia',
  Lesotho: 'Africa',
  Liberia: 'Africa',
  Libya: 'Africa',
  Lithuania: 'Europe',
  Luxembourg: 'Europe',
  Macedonia: 'Europe',
  Madagascar: 'Africa',
  Malawi: 'Africa',
  Malaysia: 'Asia',
  Mali: 'Africa',
  Mauritania: 'Africa',
  Mexico: 'North America',
  Moldova: 'Europe',
  Mongolia: 'Asia',
  Montenegro: 'Europe',
  Morocco: 'Africa',
  Mozambique: 'Africa',
  Myanmar: 'Asia',
  'N. Cyprus': 'Europe',
  Namibia: 'Africa',
  Nepal: 'Asia',
  Netherlands: 'Europe',
  'New Caledonia': 'Oceania',
  'New Zealand': 'Oceania',
  Nicaragua: 'North America',
  Niger: 'Africa',
  Nigeria: 'Africa',
  'North Korea': 'Asia',
  Norway: 'Europe',
  Oman: 'Asia',
  Pakistan: 'Asia',
  Palestine: 'Asia',
  Panama: 'North America',
  'Papua New Guinea': 'Oceania',
  Paraguay: 'South America',
  Peru: 'South America',
  Philippines: 'Asia',
  Poland: 'Europe',
  Portugal: 'Europe',
  'Puerto Rico': 'North America',
  Qatar: 'Asia',
  Romania: 'Europe',
  Russia: 'Europe',
  Rwanda: 'Africa',
  'S. Sudan': 'Africa',
  'Saudi Arabia': 'Asia',
  Senegal: 'Africa',
  Serbia: 'Europe',
  'Sierra Leone': 'Africa',
  Slovakia: 'Europe',
  Slovenia: 'Europe',
  'Solomon Is.': 'Oceania',
  Somalia: 'Africa',
  Somaliland: 'Africa',
  'South Africa': 'Africa',
  'South Korea': 'Asia',
  Spain: 'Europe',
  'Sri Lanka': 'Asia',
  Sudan: 'Africa',
  Suriname: 'South America',
  Sweden: 'Europe',
  Switzerland: 'Europe',
  Syria: 'Asia',
  Taiwan: 'Asia',
  Tajikistan: 'Asia',
  Tanzania: 'Africa',
  Thailand: 'Asia',
  'Timor-Leste': 'Asia',
  Togo: 'Africa',
  'Trinidad and Tobago': 'North America',
  Tunisia: 'Africa',
  Turkey: 'Asia',
  Turkmenistan: 'Asia',
  Uganda: 'Africa',
  Ukraine: 'Europe',
  'United Arab Emirates': 'Asia',
  'United Kingdom': 'Europe',
  'United States of America': 'North America',
  Uruguay: 'South America',
  Uzbekistan: 'Asia',
  Vanuatu: 'Oceania',
  Venezuela: 'South America',
  Vietnam: 'Asia',
  'W. Sahara': 'Africa',
  Yemen: 'Asia',
  Zambia: 'Africa',
  Zimbabwe: 'Africa',
  eSwatini: 'Africa',

  // aliases: our dataset's naming differs from the map dataset, or the
  // country has no distinct shape in the low-res map data
  'United States': 'North America',
  'Czech Republic': 'Europe',
  'Hong Kong': 'Asia',
  Singapore: 'Asia',
};

export function countryContinent(name) {
  return COUNTRY_CONTINENT[name] || null;
}
